# novnc-deployment.yml
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ocpdoom
  name: novnc
  labels:
    app: novnc

spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc
  template:
    metadata:
      labels:
        app: novnc
    spec:
      containers:
        - image: jhankins/docker-novnc:latest
          imagePullPolicy: IfNotPresent
          name: novnc
          args:
            - --vnc
            - ocpdoom:5900
          ports:
            - name: novnc
              containerPort: 6080
      restartPolicy: Alway
